#!/bin/bash
# sent files to VM
if read -t 10 -p "sent project to VM? (y/n) " ans
then
case $ans in
y) scp -r -P 2222 ~/Desktop/init user@127.0.0.1:~/Desktop ;;
n)  echo
	echo "OK :( ";;
esac
else
	echo
	echo "too slow..."
fi
